use_default_settings: true

server:
  secret_key: "__SEARXNG_SECRET__"

search:
  formats:
    - html
    - json

# Default DOI resolver required by searxng configuration
default_doi_resolver: "oadoi.org"
